name = "SymbolicInference"
uuid = "0c4721b3-3133-403d-859d-6fdff663af57"
authors = ["= <=> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
